pipeline{
    agent any
    tools {
  maven 'maven3.9'
  }

stages {
  stage('code compile') {
    steps {
        git 'https://github.com/Mcdans1/samplejavaapp'
      sh 'mvn compile'
    }
  }

  stage('code review') {
    steps {
      sh 'mvn pmd:pmd'
    }
    post {
      success {
        recordIssues sourceCodeRetention: 'LAST_BUILD', tools: [pmdParser(pattern: '**/pmd.xml')]
      }
    }
  }

  stage('unit test') {
    steps {
      sh 'mvn test'
    }
    post {
      success {
        junit stdioRetention: '', testResults: 'myproject/target/test-reports/*.xml'
      }
    }
  }

  stage('code coverage') {
    steps {
      sh 'mvn verify'
    }
    post {
      success {
        jacoco maximumClassCoverage: '20', maximumLineCoverage: '80', minimumComplexityCoverage: '50'
      }
    }
  }

  stage('package') {
    steps {
      sh 'mvn package'
    }
  }

}


}
